Exlicitely set resultBundlePath for xcodebuild.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -13,8 +13,9 @@ workflows:
     - errcheck:
     - go-test:
     after_run:
+    # headless tests first, as otherwise running emulator is reused
     - ci-objc_headless_mode
-    - ci-objc_headless_mode_failing_ui_test
+    - ci-objc_headless_mode_xcpretty
     - ci-xcode-8_headless_mode
     - ci-parallel_headless_mode
     - tvos_headless_mode
@@ -22,6 +23,9 @@ workflows:
     - ci-xcode-8
     - ci-parallel
     - tvos
+    # failing ui test is last, so does not stop the other testcases from running
+    - ci-objc_headless_mode_failing_ui_test
+
   
   xcode_8_ci: 
     before_run:
@@ -37,6 +41,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
     - BITRISE_SCHEME: ios-simple-objc
     - SIMULATOR_DEVICE: iPhone 6 Plus
@@ -46,23 +51,40 @@ workflows:
     - _test
     - check_exported_artifacts
 
-    ci-objc_headless_mode_failing_ui_test:
-      envs:
-      - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
-      - SAMPLE_APP_BRANCH: failing-ui-test
-      - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
-      - BITRISE_SCHEME: ios-simple-objc
-      - SIMULATOR_DEVICE: iPhone 6 Plus
-      - SIMULATOR_PLATFORM: iOS Simulator
-      - HEADLESS_MODE: "yes"
-      after_run:
-      - _test
-      - check_exported_artifacts
+  ci-objc_headless_mode_xcpretty:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
+    - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcpretty
+    - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
+    - BITRISE_SCHEME: ios-simple-objc
+    - SIMULATOR_DEVICE: iPhone 6 Plus
+    - SIMULATOR_PLATFORM: iOS Simulator
+    - HEADLESS_MODE: "yes"
+    after_run:
+    - _test
+    - check_exported_artifacts
+    - check_xcpretty_html_report
+
+  ci-objc_headless_mode_failing_ui_test:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
+    - SAMPLE_APP_BRANCH: failing-ui-test
+    - OUTPUT_TOOL: xcodebuild
+    - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
+    - BITRISE_SCHEME: ios-simple-objc
+    - SIMULATOR_DEVICE: iPhone 6 Plus
+    - SIMULATOR_PLATFORM: iOS Simulator
+    - HEADLESS_MODE: "yes"
+    after_run:
+    - _test
+    - check_exported_artifacts
 
   ci-xcode-8_headless_mode:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/ios-xcode-8.0.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: ios-xcode-8.0/ios-xcode-8.0.xcodeproj
     - BITRISE_SCHEME: ios-xcode-8.0
     - SIMULATOR_DEVICE: iPhone 6 Plus
@@ -75,6 +97,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-tvos-swift.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: NPO Live.xcworkspace
     - BITRISE_SCHEME: NPO Live
     - SIMULATOR_DEVICE: Apple TV
@@ -87,6 +110,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-swift-project-with-parallel-ui-test.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: BullsEye.xcodeproj
     - BITRISE_SCHEME: BullsEye
     - HEADLESS_MODE: "yes"
@@ -97,6 +121,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
     - BITRISE_SCHEME: ios-simple-objc
     - SIMULATOR_DEVICE: iPhone 6 Plus
@@ -110,6 +135,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/ios-xcode-8.0.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: ios-xcode-8.0/ios-xcode-8.0.xcodeproj
     - BITRISE_SCHEME: ios-xcode-8.0
     - SIMULATOR_DEVICE: iPhone 6 Plus
@@ -122,6 +148,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-tvos-swift.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: NPO Live.xcworkspace
     - BITRISE_SCHEME: NPO Live
     - SIMULATOR_DEVICE: Apple TV
@@ -134,6 +161,7 @@ workflows:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-swift-project-with-parallel-ui-test.git
     - SAMPLE_APP_BRANCH: master
+    - OUTPUT_TOOL: xcodebuild
     - BITRISE_PROJECT_PATH: BullsEye.xcodeproj
     - BITRISE_SCHEME: BullsEye
     - HEADLESS_MODE: "no"
@@ -165,7 +193,7 @@ workflows:
     - certificate-and-profile-installer: {}
     - path::./:
         inputs:
-        - output_tool: xcodebuild
+        - output_tool: $OUTPUT_TOOL
         # - is_clean_build: "no"
         - is_clean_build: "yes"
         - generate_code_coverage_files: "no"
@@ -206,6 +234,22 @@ workflows:
 
             echo "Exported attachments found: $BITRISE_DEPLOY_DIR/ios-simple-objc-xc-test-Attachments.zip"
 
+  check_xcpretty_html_report:
+    steps:
+    - script:
+        title: Check xcpretty html report
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+
+            if [ ! -f $BITRISE_DEPLOY_DIR/xcode-test-results-ios-simple-objc.html ]; then
+                echo "Exported xcpretty html report - xcode-test-results-ios-simple-objc.html - not found in $BITRISE_DEPLOY_DIR"
+                exit 1
+            fi
+
+            echo "Exported xcpretty html report found: $BITRISE_DEPLOY_DIR/xcode-test-results-ios-simple-objc.html"
 
   # ----------------------------------------------------------------
   # --- Utility workflows
