feat: add the new go test steps to the workflow and a check for the exported artifacts.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -5,7 +5,6 @@ app:
   envs:
   - BITRISE_STEP_VERSION: 1.18.16
 
-  - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
   - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
   - BITRISE_SCHEME: ios-simple-objc
 
@@ -15,7 +14,11 @@ workflows:
   ci:
     before_run:
     - audit-this-step
-    - go-tests
+    steps:
+    - go-list:
+    - golint:
+    - errcheck:
+    - go-test:
     after_run:
     - ci-objc
     - ci-xcode-8
@@ -25,15 +28,16 @@ workflows:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-simple-objc-with-uitest.git
     - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
     - BITRISE_SCHEME: ios-simple-objc
-    before_run:
+    after_run:
     - test
+    - check_exported_artifacts
 
   ci-xcode-8:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/ios-xcode-8.0.git
     - BITRISE_PROJECT_PATH: ios-xcode-8.0/ios-xcode-8.0.xcodeproj
     - BITRISE_SCHEME: ios-xcode-8.0
-    before_run:
+    after_run:
     - test
 
   test:
@@ -85,6 +89,24 @@ workflows:
             fi
             echo "BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH: ${BITRISE_XCODE_RAW_TEST_RESULT_TEXT_PATH}"
             echo "BITRISE_XCODE_TEST_ATTACHMENTS_PATH: ${BITRISE_XCODE_TEST_ATTACHMENTS_PATH}"
+
+  check_exported_artifacts:
+    steps:
+    - script:
+        title: Exported attachment test
+        is_always_run: true
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e
+
+            if [ ! -f $BITRISE_DEPLOY_DIR/ios-simple-objc-xc-test-Attachments.zip ]; then
+                echo "Exported artifacts - ios-simple-objc-xc-test-Attachments.zip - not found in $BITRISE_DEPLOY_DIR"
+                exit 1
+            fi
+
+            echo "Exported attachments found: $BITRISE_DEPLOY_DIR/ios-simple-objc-xc-test-Attachments.zip"
+            
 
   go-tests:
     steps:
