STEP-1205: Add Relaunch Tests for Each Repetition step input (#175)
* Added relaunch_tests_for_each_repetition in step.yml

* Added RelaunchTestsForEachRepetition to every model struct + input validation

* Add xcodebuild parameter based on RelaunchTestsForEachRepetition

* Change validation for relaunch_tests_for_each_repetition input

* Added E2E test for input validation

* Added E2E test for relaunching tests

* Updated step input titles and descriptions

* Updated step input titles

* Addressed PR comments

* Update sample app branch to master in E2E test

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -257,6 +257,51 @@ workflows:
     after_run:
     - _run
 
+  test_relaunch_tests_for_each_repetition_not_available_if_test_repetition_mode_is_none:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -lt 13 ]]; then
+              echo "This test case requires Xcode >= 13, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_13 --value "true"
+    - script:
+        title: Start a failing workflow, wrapped in a script.
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_13" "true"}}'
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_test_relaunch_tests_for_each_repetition_not_available_if_test_repetition_mode_is_none
+            if [ $? -ne 1 ] ; then
+              echo "Workflow was expected to fail, exit code not 1."
+              exit 1
+            fi
+
+  utility_test_relaunch_tests_for_each_repetition_not_available_if_test_repetition_mode_is_none:
+    envs:
+    - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
+    - TEST_APP_BRANCH: master
+    - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
+    - BITRISE_SCHEME: BullsEye
+    - XCODE_SIMULATOR_DEVICE: iPhone 8 Plus
+    - XCODE_SIMULATOR_OS_VERSION: "latest"
+    - XCODE_SIMULATOR_PLATFORM: iOS Simulator
+    - SINGLE_BUILD: "true"
+    - XCODE_OUTPUT_TOOL: xcodebuild
+    - RETRY_ON_FAILURE: "no"
+    - TEST_REPETITION_MODE: "none"
+    - RELAUNCH_TESTS_FOR_EACH_REPETITION: "yes"
+    - CACHE_LEVEL: "swift_packages"
+    after_run:
+    - _run
+
   test_should_retry_test_on_fail_succeeds:
     before_run:
     - _expose_xcode_version
@@ -825,6 +870,50 @@ workflows:
     - _run
     - _check_outputs
 
+  test_relaunch_tests_for_each_repetition_succeeds:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -lt 13 ]]; then
+              echo "This test case requires Xcode >= 13, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_13 --value "true"
+    - bitrise-run:
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_13" "true"}}'
+        inputs:
+        - workflow_id: utility_test_relaunch_tests_for_each_repetition_succeeds
+        - bitrise_config_path: ./e2e/bitrise.yml
+
+  utility_test_relaunch_tests_for_each_repetition_succeeds:
+    envs:
+    - TEST_APP_NUMBER_OF_INITIAL_TEST_SUCCESSES: 1
+    - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
+    - TEST_APP_BRANCH: master
+    - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
+    - BITRISE_SCHEME: BullsEye
+    - TEST_PLAN: "EventuallyFailingInMemoryTests"
+    - XCODE_SIMULATOR_DEVICE: iPhone 8 Plus
+    - XCODE_SIMULATOR_OS_VERSION: "latest"
+    - XCODE_SIMULATOR_PLATFORM: iOS Simulator
+    - SINGLE_BUILD: "true"
+    - XCODE_OUTPUT_TOOL: xcodebuild
+    - TEST_REPETITION_MODE: "up_until_maximum_repetitions"
+    - MAXIMUM_TEST_REPETITIONS: 2
+    - RELAUNCH_TESTS_FOR_EACH_REPETITION: "yes"
+    - RETRY_ON_FAILURE: "no"
+    - EXPECT_TEST_FAILURE: "false"
+    - CACHE_LEVEL: "swift_packages"
+    after_run:
+    - _set_number_of_initial_test_successes_in_test_app
+    - _run
+    - _check_outputs
+
   test_simulator_os_version:
     before_run:
     - _expose_xcode_version
@@ -965,12 +1054,19 @@ workflows:
             set -eo pipefail
             envman add --key TEST_REPETITION_MODE --value ${TEST_REPETITION_MODE-none}
     - script:
-        title: Set MAXIMUM_TEST_REPETITIONS to 3 if not set
+        title: Set MAXIMUM_TEST_REPETITIONS to '3' if not set
         inputs:
         - content: |-
             #!/bin/env bash
             set -eo pipefail
             envman add --key MAXIMUM_TEST_REPETITIONS --value ${MAXIMUM_TEST_REPETITIONS-3}
+    - script:
+        title: Set RELAUNCH_TESTS_FOR_EACH_REPETITION to 'no' if not set
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -eo pipefail
+            envman add --key RELAUNCH_TESTS_FOR_EACH_REPETITION --value ${RELAUNCH_TESTS_FOR_EACH_REPETITION-no}
     - path::./:
         inputs:
         - project_path: ./_tmp/$BITRISE_PROJECT_PATH
@@ -978,6 +1074,7 @@ workflows:
         - test_plan: $TEST_PLAN
         - test_repetition_mode: $TEST_REPETITION_MODE
         - maximum_test_repetitions: $MAXIMUM_TEST_REPETITIONS
+        - relaunch_tests_for_each_repetition: $RELAUNCH_TESTS_FOR_EACH_REPETITION
         - simulator_device: $XCODE_SIMULATOR_DEVICE
         - simulator_os_version: $XCODE_SIMULATOR_OS_VERSION
         - simulator_platform: $XCODE_SIMULATOR_PLATFORM
