Fix yaml lint issues

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -43,26 +43,26 @@ workflows:
     - _expose_xcode_version
     steps:
     - bitrise-run:
-        run_if: '{{getenv "XCODE_MAJOR_VERSION" | ne "26"}}'
+        run_if: {{getenv "XCODE_MAJOR_VERSION" | ne "26"}}
         inputs:
         - workflow_id: utility_test_test_plan
         - bitrise_config_path: ./e2e/bitrise.yml
 
   utility_test_test_plan:
-      envs:
-      - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
-      - TEST_APP_BRANCH: master
-      - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
-      - BITRISE_SCHEME: BullsEye
-      - TEST_PLAN: UnitTests
-      - DESTINATION: platform=iOS Simulator,name=Bitrise iOS default,OS=latest
-      - LOG_FORMATTER: xcbeautify
-      - EXPECT_TEST_FAILURE: "false"
-      - CACHE_LEVEL: swift_packages
-      after_run:
-      - _run
-      - _check_outputs
-      - _check_cache
+    envs:
+    - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
+    - TEST_APP_BRANCH: master
+    - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
+    - BITRISE_SCHEME: BullsEye
+    - TEST_PLAN: UnitTests
+    - DESTINATION: platform=iOS Simulator,name=Bitrise iOS default,OS=latest
+    - LOG_FORMATTER: xcbeautify
+    - EXPECT_TEST_FAILURE: "false"
+    - CACHE_LEVEL: swift_packages
+    after_run:
+    - _run
+    - _check_outputs
+    - _check_cache
 
   test_xcconfig_rel_path:
     envs:
@@ -278,23 +278,23 @@ workflows:
             fi
 
   _expose_xcode_version:
-      steps:
-      - script:
-            title: Expose Xcode major version
-            inputs:
-            - content: |-
-                  #!/bin/env bash
-                  set -e
-                  if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
-                    echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
-                    exit 0
-                  fi
-                  version=`xcodebuild -version`
-                  regex="Xcode ([0-9]*)."
-                  if [[ ! $version =~ $regex ]]; then
-                    echo "Failed to determine Xcode major version"
-                    exit 1
-                  fi
-                  xcode_major_version=${BASH_REMATCH[1]}
-                  echo "Xcode major version: $xcode_major_version"
-                  envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
+    steps:
+    - script:
+        title: Expose Xcode major version
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
+              echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
+              exit 0
+            fi
+            version=`xcodebuild -version`
+            regex="Xcode ([0-9]*)."
+            if [[ ! $version =~ $regex ]]; then
+              echo "Failed to determine Xcode major version"
+              exit 1
+            fi
+            xcode_major_version=${BASH_REMATCH[1]}
+            echo "Xcode major version: $xcode_major_version"
+            envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
