Added E2E tests for checking non-available step inputs on selected stacks

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -172,6 +172,94 @@ workflows:
     - _check_outputs
     - _check_cache
 
+  test_retry_on_failure_not_available_above_xcode_13:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -lt 13 ]]; then
+              echo "This test case requires Xcode >= 13, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_13 --value "true"
+    - script:
+        title: Start a failing workflow, wrapped in a script.
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_13" "true"}}'
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_test_retry_on_failure_not_available_above_xcode_13
+            if [ $? -ne 1 ] ; then
+              echo "Workflow was excepted to fail, exit code not 1."
+              exit 1
+            fi
+
+  utility_test_retry_on_failure_not_available_above_xcode_13:
+    envs:
+    - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
+    - TEST_APP_BRANCH: master
+    - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
+    - BITRISE_SCHEME: BullsEye
+    - XCODE_SIMULATOR_DEVICE: iPhone 8 Plus
+    - XCODE_SIMULATOR_OS_VERSION: "latest"
+    - XCODE_SIMULATOR_PLATFORM: iOS Simulator
+    - SINGLE_BUILD: "true"
+    - XCODE_OUTPUT_TOOL: xcodebuild
+    - RETRY_ON_FAILURE: "yes"
+    - CACHE_LEVEL: "swift_packages"
+    after_run:
+    - _run
+    - _check_outputs
+
+  test_repetition_mode_not_available_below_xcode_13:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -gt 12 ]]; then
+              echo "This test case requires Xcode <= 12, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_AT_MOST_12 --value "true"
+    - script:
+        title: Start a failing workflow, wrapped in a script.
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_MOST_12" "true"}}'
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_test_repetition_mode_not_available_below_xcode_13
+            if [ $? -ne 1 ] ; then
+              echo "Workflow was excepted to fail, exit code not 1."
+              exit 1
+            fi
+
+  utility_test_repetition_mode_not_available_below_xcode_13:
+    envs:
+      - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
+      - TEST_APP_BRANCH: master
+      - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
+      - BITRISE_SCHEME: BullsEye
+      - XCODE_SIMULATOR_DEVICE: iPhone 8 Plus
+      - XCODE_SIMULATOR_OS_VERSION: "latest"
+      - XCODE_SIMULATOR_PLATFORM: iOS Simulator
+      - SINGLE_BUILD: "true"
+      - XCODE_OUTPUT_TOOL: xcodebuild
+      - RETRY_ON_FAILURE: "yes"
+      - CACHE_LEVEL: "swift_packages"
+    after_run:
+    - _run
+    - _check_outputs
+
   test_retry_succeeds:
     before_run:
     - _expose_xcode_version
