Test Quarantine (#262)
* Use flakyTestCasesEnvVarSizeLimitInBytes instead of hardcoded value

* Introduce skip_tests step input

* Add tests for test skipping

* Fix yaml lint issue and add tests for skip tests input value parsing

* Rename skip testing input

* README update

* Support skip testing file config

* Update skip_testing input category

* Fix skip testing flag

* Quarantine tests

* Update README

* Fix lint issue

* Fix go lint issues

* Code cleanup

* Code cleanup

* Add test_skip_testing e2e test

* Rename test_skip_testing e2e test

* Merge test_test_plan and test_quarantined_tests

* Skip test_plan test on Xcode 26

* Fix function comment

* Update go-steputils

* Don't run test_xcconfig_rel_path on Xcode 26

* Update Quarantined tests input

* Reenable test_test_plan and test_xcconfig_rel_path e2e tests on Xcode 26

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -34,36 +34,52 @@ workflows:
     - _check_exported_artifacts
     - _check_xcpretty_html_report
 
-  # Requires Xcode 11+
   test_test_plan:
-    description: |-
-        This test fails on Xcode 26 with: 'BullsEye (33951) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying Error: Crash: BullsEye (33951) <external symbol>))' error.
-        Example build: https://app.bitrise.io/build/c71f9c3a-e164-423f-8779-d4c8db69827a
-    before_run:
-    - _expose_xcode_version
-    steps:
-    - bitrise-run:
-        run_if: |-
-          {{ getenv "XCODE_MAJOR_VERSION" | ne "26" }}
-        inputs:
-        - workflow_id: utility_test_test_plan
-        - bitrise_config_path: ./e2e/bitrise.yml
-
-  utility_test_test_plan:
     envs:
     - TEST_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
     - TEST_APP_BRANCH: master
     - BITRISE_PROJECT_PATH: BullsEye.xcworkspace
     - BITRISE_SCHEME: BullsEye
-    - TEST_PLAN: UnitTests
+    - TEST_PLAN: UITests
     - DESTINATION: platform=iOS Simulator,name=Bitrise iOS default,OS=latest
     - LOG_FORMATTER: xcbeautify
     - EXPECT_TEST_FAILURE: "false"
     - CACHE_LEVEL: swift_packages
-    after_run:
+    - QUARANTINED_TESTS: |-
+        [
+          {
+            "testCaseName": "testGameStyleSwitch()",
+            "testSuiteName": [
+              "BullsEyeUITests"
+            ],
+            "className": "BullsEyeUITests2"
+          }
+        ]
+    before_run:
     - _run
     - _check_outputs
     - _check_cache
+    steps:
+    - script:
+        title: Check skipped tests
+        summary: This Step checks if the test results contain the skipped test method or not.
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+            out=$(xcrun xcresulttool get test-results tests --path "$BITRISE_XCRESULT_PATH")
+            xcresulttool_exit_code=$?
+            if [ $xcresulttool_exit_code -ne 0 ]; then
+              echo "failed to get test results from xcresult: $out"
+              exit 1
+            fi
+            # Check if the skipped test method is in the results
+            set +e
+            grep_out=$(echo "$out" | grep "BullsEyeUITests2/testGameStyleSwitch()")
+            if [ ! -z "$grep_out" ]; then
+              echo "skipped test method found in test results"
+              exit 1
+            fi
 
   test_xcconfig_rel_path:
     envs:
@@ -77,14 +93,10 @@ workflows:
     - EXPECT_TEST_FAILURE: "false"
     - CACHE_LEVEL: none
     - XCCONFIG_CONTENT: ./_tmp2/p.xcconfig
-    before_run:
-    - utility_create_xcconfig
     after_run:
     - _run
     - _check_outputs
     - _check_exported_artifacts
-
-  utility_create_xcconfig:
     steps:
     - script:
         inputs:
@@ -159,6 +171,7 @@ workflows:
         - verbose_log: "yes"
         - cache_level: $CACHE_LEVEL
         - collect_simulator_diagnostics: $COLLECT_SIM_DIAGNOSTICS
+        - quarantined_tests: $QUARANTINED_TESTS
 
   _clear_outputs:
     steps:
@@ -277,25 +290,3 @@ workflows:
                 echo "BITRISE_CACHE_INCLUDE_PATHS is empty"
                 exit 1
             fi
-
-  _expose_xcode_version:
-    steps:
-    - script:
-        title: Expose Xcode major version
-        inputs:
-        - content: |-
-            #!/bin/env bash
-            set -e
-            if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
-              echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
-              exit 0
-            fi
-            version=`xcodebuild -version`
-            regex="Xcode ([0-9]*)."
-            if [[ ! $version =~ $regex ]]; then
-              echo "Failed to determine Xcode major version"
-              exit 1
-            fi
-            xcode_major_version=${BASH_REMATCH[1]}
-            echo "Xcode major version: $xcode_major_version"
-            envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
