Updated E2E tests to not run on Xcode 13

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -184,40 +184,16 @@ workflows:
             if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
               echo "This test case requires Xcode >= 11, skipping..."
               exit 0
+            elif [[ $XCODE_MAJOR_VERSION -gt 12 ]]; then
+              echo "This test case requires Xcode <= 12, skipping..."
+              exit 0
             fi
-            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
+            envman add --key XCODE_MAJOR_VERSION_BETWEEN_11_AND_12 --value "true"
     - bitrise-run:
-        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_BETWEEN_11_AND_12" "true"}}'
         inputs:
         - workflow_id: utility_test_retry_succeeds
         - bitrise_config_path: ./e2e/bitrise.yml
-
-  test_retry_fails:
-    before_run:
-    - _expose_xcode_version
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/env bash
-            set -e
-            if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
-              echo "This test case requires Xcode >= 11, skipping..."
-              exit 0
-            fi
-            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
-    - script:
-        title: Start a failing workflow, wrapped in a script.
-        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
-        inputs:
-          - content: |-
-              #!/bin/env bash
-              set -x # Do not set -e as bitrise command is expected to fail
-              bitrise run --config=./e2e/bitrise.yml utility_test_retry_fails
-              if [ $? -ne 1 ] ; then
-                echo "Workflow was excepted to fail, exit code not 1."
-                exit 1
-              fi
 
   utility_test_retry_succeeds:
     envs:
@@ -239,6 +215,36 @@ workflows:
     - _set_number_of_flaky_tests_in_test_app
     - _run
     - _check_outputs
+
+  test_retry_fails:
+    before_run:
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
+              echo "This test case requires Xcode >= 11, skipping..."
+              exit 0
+            elif [[ $XCODE_MAJOR_VERSION -gt 12 ]]; then
+              echo "This test case requires Xcode <= 12, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_BETWEEN_11_AND_12 --value "true"
+    - script:
+        title: Start a failing workflow, wrapped in a script.
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_BETWEEN_11_AND_12" "true"}}'
+        inputs:
+          - content: |-
+              #!/bin/env bash
+              set -x # Do not set -e as bitrise command is expected to fail
+              bitrise run --config=./e2e/bitrise.yml utility_test_retry_fails
+              if [ $? -ne 1 ] ; then
+                echo "Workflow was expected to fail, exit code not 1."
+                exit 1
+              fi
 
   utility_test_retry_fails:
     envs:
@@ -273,11 +279,14 @@ workflows:
             if [[ ${XCODE_MAJOR_VERSION} -lt 11 ]]; then
               echo "This test case requires Xcode >= 11, skipping..."
               exit 0
+            elif [[ $XCODE_MAJOR_VERSION -gt 12 ]]; then
+              echo "This test case requires Xcode <= 12, skipping..."
+              exit 0
             fi
-            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_11 --value "true"
+            envman add --key XCODE_MAJOR_VERSION_BETWEEN_11_AND_12 --value "true"
     - script:
         title: Start a failing workflow, wrapped in a script.
-        run_if: '{{enveq "XCODE_MAJOR_VERSION_AT_LEAST_11" "true"}}'
+        run_if: '{{enveq "XCODE_MAJOR_VERSION_BETWEEN_11_AND_12" "true"}}'
         inputs:
           - content: |-
               #!/bin/env bash
